version: "3.7"
services:
  local-qa-db:
    image: "local:qa:db"
    container_name: local_qa_db
    restart: "always"
    build: ./
    ports:
      - "3345:3345"
    network_mode: bridge
    # environment:
    #   - APP_PORT=${APP_PORT}
    #   - SHERLOCK_PROD_BASE_API=${API_COM_PROD_BASE_API}
    #   - SHERLOCK_BETA_BASE_API=${API_COM_BETA_BASE_API}