version: "3.7"
services:
  local-qa-db:
    image: "local:qa"
    container_name: local_qa_db
    restart: "always"
    build: ./
    ports:
      - "3347:3347"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]